DROP DATABASE IF EXISTS CineMatchMe;
CREATE DATABASE DROP DATABASE IF EXISTS CineMatchMe;
;

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+02:00";
USE CineMatchMe;

DROP TABLE IF EXISTS 'Movie';
CREATE TABLE Movie
(
  Movie_ID INT NOT NULL,
  Title VARCHAR NOT NULL,
  Actors VARCHAR NOT NULL,
  Plot VARCHAR NOT NULL,
  PRIMARY KEY (Movie_ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

DROP TABLE IF EXISTS 'User';
CREATE TABLE User
(
  User_ID INT NOT NULL,
  Statistics VARCHAR NOT NULL,
  Renown INT NOT NULL,
  Surname VARCHAR NOT NULL,
  email VARCHAR NOT NULL,
  Name VARCHAR NOT NULL,
  PRIMARY KEY (User_ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

DROP TABLE IF EXISTS 'Subscription';
CREATE TABLE Subscription
(
  Price FLOAT(3,2) NOT NULL,
  Tier ENUM('Free','Lite','Premium') NOT NULL,
  Duration INT NOT NULL,
  User_ID INT NOT NULL,
  PRIMARY KEY (User_ID),
  FOREIGN KEY (User_ID) REFERENCES User(User_ID)
  ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

DROP TABLE IF EXISTS 'Place';
CREATE TABLE Place
(
  Place_ID INT NOT NULL,
  Name VARCHAR NOT NULL,
  Location VARCHAR NOT NULL,
  Current_Movies VARCHAR NOT NULL,
  PRIMARY KEY (Place_ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

DROP TABLE IF EXISTS 'plays';
CREATE TABLE plays
(
  Place_ID INT NOT NULL,
  Movie_ID INT NOT NULL,
  PRIMARY KEY (Place_ID, Movie_ID),
  FOREIGN KEY (Place_ID) REFERENCES Place(Place_ID)
  ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (Movie_ID) REFERENCES Movie(Movie_ID)
  ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

DROP TABLE IF EXISTS 'reviews';
CREATE TABLE reviews
(
  User_ID INT NOT NULL,
  Movie_ID INT NOT NULL,
  PRIMARY KEY (User_ID, Movie_ID),
  FOREIGN KEY (User_ID) REFERENCES User(User_ID)
  ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (Movie_ID) REFERENCES Movie(Movie_ID)
  ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

DROP TABLE IF EXISTS 'isFriendsWith';
CREATE TABLE isFriendsWith
(
  User_ID_1 INT NOT NULL,
  User_ID_2 INT NOT NULL,
  PRIMARY KEY (User_ID_1, isFriendsWithUser_ID_2),
  FOREIGN KEY (User_ID_1) REFERENCES User(User_ID)
  ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (User_ID_2) REFERENCES User(User_ID)
  ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

