DROP PROCEDURE IF EXISTS loginCheck;
DELIMITER $
CREATE PROCEDURE loginCheck(email VARCHAR(255), password VARCHAR(255) )
BEGIN
	SELECT password FROM `User`
	WHERE User.email = email;
END $
DELIMITER ;

DROP PROCEDURE IF EXISTS registerUser;
DELIMITER $
CREATE PROCEDURE registerUser(name VARCHAR(255), surname VARCHAR(255),
								email VARCHAR(255), password VARCHAR(255))
BEGIN
	INSERT INTO `User` VALUES
	(DEFAULT,email,password,name,surname,DEFAULT,0);
END $
DELIMITER ;

DROP PROCEDURE IF EXISTS addFriend;
DELIMITER $
CREATE PROCEDURE addFriend(user1 VARCHAR(255), user2 VARCHAR(255))
BEGIN
	INSERT INTO isFriendsWith VALUES (user1,user2);
END $
DELIMITER ;

DROP PROCEDURE IF EXISTS removeFriend;
DELIMITER $
CREATE PROCEDURE removeFriend(user1 VARCHAR(255), user2 VARCHAR(255))
BEGIN
	DELETE FROM `isFriendsWith` 
	WHERE User_ID_1 = user1 AND User_ID_2 = user2;
END $
DELIMITER ;

DROP PROCEDURE IF EXISTS suggestMovie;
DELIMITER $
CREATE PROCEDURE suggestMovie(movie_title VARCHAR(255))
BEGIN
	INSERT INTO moviesToAdd VALUES (movie_title,DEFAULT);
END $
DELIMITER ;


